name: Npm Publish Utils

on:
  release:
    types: [released]

jobs:
  publish:
    uses: dymexjs/reusable_workflows/.github/workflows/publish-npm.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    permissions:
      id-token: write
      contents: read
